############################################################################

branches:
    except:
    - staging.tmp
    - trying.tmp

env:
    global:
        - DOCUMENTER_DEBUG="true"
        - DOCKER_IMAGE_OWNER="dilumaluthge"
        - JULIA_DEBUG="all"
        - PREDICTMD_OPEN_PLOTS_DURING_TESTS="true"

git:
    depth: 99999999

language: bash

matrix:
    fast_finish: true

notifications:
    email:
        on_failure: always
        on_success: never
os:
    - linux

services:
    - docker

############################################################################

before_install:
    - true
install:
    - true
before_script:
    - true
script:
    - true
after_script:
    - true

############################################################################

stages:
    - stage-1
    - stage-2
    - stage-3

############################################################################

jobs:
    include:
        - stage: stage-1
          name: "dilumaluthge/julia1.1"
          env:
              - IMAGE="julia1.1"
              - FOLDER="julia"
          script: ./ci/travis/script.sh
        - stage: stage-2
          name: "dilumaluthge/latex_for_plotting"
          env:
              - IMAGE="latex_for_plotting"
              - FOLDER="tex"
          script: ./ci/travis/script.sh
        - stage: stage-3
          name: "dilumaluthge/predictmd_stable"
          env:
              - IMAGE="predictmd_stable"
              - FOLDER="predictmd"
          script: true
        - stage: stage-3
          name: "dilumaluthge/predictmd_unstable"
          env:
              - IMAGE="predictmd_unstable"
              - FOLDER="predictmd"
          script: ./ci/travis/script.sh

############################################################################
